### ISSUE TITLE
Retail Failing 

### ISSUE THREAD

**Issue by ohlawdie** [Witnesscm/InboxMailBag#1]
Hey Witnessscm, 

I'm unsure if you've had the chance to test this in retail wow but it doesn't appear to be working/ showing the tab at the bottom of the mail. I'm on this latest version 

24x Interface/AddOns/InboxMailbag/InboxMailBag.lua:34: Usage: GetItemClassInfo(itemClassID)
[string "=[C]"]: in function `GetItemClassInfo'
[string "@Interface/AddOns/InboxMailbag/InboxMailBag.lua"]:34: in main chunk

Locals:
(*temporary) = nil

OnLoad, OnShow, OnHide all functions failing

Happy Turkey Day!

**Comment by Witnesscm** [comment]
Hi, this issue should have been fixed in https://github.com/Witnesscm/InboxMailBag/commit/8e43f35e12aa57086ce034298fd30e18129d1049. Are you sure it's version 2.5.1 ?

**Comment by ohlawdie** [comment]
ah no it wasn't the correct version I apologize, thank you!
